### PR TITLE
Update SyncDings.

### PR DESCRIPTION
**Pull request by valariems**
This is the sister PR for orgsync/orgsync: https://github.com/orgsync/orgsync/pull/8739

### CODE REVIEW

**Comment by caseywebdev** [comment]
Does this add or remove any icons or just change existing ones?

**Comment by valariems** [comment]
Adds two icons. Hold off on merging it in, though. I'm going to make additional changes to it.

**Comment by caseywebdev** [comment]
Alright, we'll also want to add those icons to the appropriate SCSS files in the `styles/syncdings` folder.

**Comment by valariems** [comment]
Okaym thanks. We need to update the Wiki to give instructions for that https://github.com/orgsync/orgsync/wiki/How-to-build-the-OrgSync-Icon-Font. The Wiki currently reads "In velcro, do something. Update this guide when that something is figured out." That's why I was just updating the font so that the version of the font would match in both OrgSync and Velcro repositories.

**Comment by tylerlee** [comment]
just a note that i just started a PR to make the web app use velcro syncdings so we don't have to do this anymore. https://github.com/orgsync/orgsync/pull/8755

**Comment by valariems** [comment]
Closing. This is old and syncdings has been updated since this PR.

**Pull request closed without merging**
